[tool.poetry]
name = "fastui-blog-template"
version = "0.1.0"
description = ""
authors = ["kwon-evan <koun012@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
